name: cowsay
description: Simple library to print message in cow balloon.
version: 0.0.1-alpha

repository: https://github.com/rickypid/cowsay

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
