const List<String> figure = [
  '                                        ',
  '                    +ddddddddddy        ',
  '                  +mh-     .yNo`        ',
  '                +mh-     .yNo`          ',
  '              +mh-     .yNo`            ',
  '            +mh-     .yNo`              ',
  '          +mh-     .yNo`                ',
  '        +mh-     .yNo`                  ',
  '      +mh-     .yNo`  ----------`       ',
  '    +mh-     .yNo`  +mhsssssshMN+       ',
  '    +mh-   .yNo`  +mh-     .yNo`        ',
  '      +mh:yNo`  +mh-     .yNo`          ',
  '        +do`  +mh-     .yNo`            ',
  '            +mh-     .yNo`              ',
  '            +mh-   .yNhNo`              ',
  '              +mh:yNo` .yNo`            ',
  '                +mN:     .yNo`          ',
  '                  +mh-     .yNo`        ',
  '                    +mhsssssshMN+       ',
  '                      ----------`       ',
];
